### ISSUE TITLE
Remove the need to manually update encTitlekeys.bin

### ISSUE THREAD

**Issue by astronautlevel2** [MatMaf/encTitleKeys.bin-Updater#1]
Your problems with downloading from the titlekey site are due to the site enforcing https, which the stable release of lpp-3ds does not support. This leaves you with a few potential options:

1. Write a bash script or similar to automatically download the file and rehost it
2. Update to a newer version of lpp-3ds that does support https.

Typically it's best to not have to manually update these things.

**Comment by MatMaf** [comment]
I tried with the latest nightly but I couldn't get it to work. I'll try it again for 1.1.

**Comment by astronautlevel2** [comment]
If it doesn't work I could make a bash script that automatically downloads and rehosts the encTitleKeys.bin on my website.

**Comment by MatMaf** [comment]
Could you do that but for my gh-pages branch? I need the URL to stay the same so it continues to work across all versions.

I'm assuming you know vb.net? Here's the code I use to download the required zip to my PC. I would love it if you could convert it to batch and get it to auto-upload: [encTitleKeysUpdater v1 zip handler.zip](https://github.com/MatMaf/encTitleKeys.bin-Updater/files/298600/encTitleKeysUpdater.v1.zip.handler.zip)

**Comment by astronautlevel2** [comment]
Downloading and updating the encTitleKeys.bin should be fairly easy from a batch script:

`cd <path-to-local-directory>
git checkout gh-pages
del /F /Q f4g5h6.zip
del /F /Q encTitleKeys.bin
wget https://3ds.titlekeys.com/downloadenc -O encTitleKeys.bin
move encTitleKeys.bin a1s2d3.bin
zip f4g5h6.zip a1s2d3.bin
git add f4g5h6.zip
git commit -m "Updated encTitleKeys.bin automatically
git push`

This requires wget installed to download, and ssh for git setup so it won't prompt you for your github login.

**Comment by ksanislo** [comment]
I patched up lpp-3ds with much better networking support, so you'll have working https:// if you upgrade what you're building with here.

**Comment by MatMaf** [comment]
It's not https://

Rinne said it's to with with subdomains, and that lpp-3ds can't resolve the host because titlekeys.com has "3ds." before it.

**Comment by ksanislo** [comment]
There's no reason it won't work, I revamped networking in LPP late last week, there's no reason it won't do exactly what you want now.

**Comment by MatMaf** [comment]
[index.zip](https://github.com/MatMaf/encTitleKeys.bin-Updater/files/370384/index.zip)

This is the script I'm using, along with the .elf I'm using. The download always fails. I made sure to get the latest nightly. Do you know what's wrong? I've tried both http and https.

**Comment by ksanislo** [comment]
well I'll be damned, i'm not sure wtf is screwy, here's a copy of lpp built from my fork before anything was changed, it works for me.

http://home.intherack.com/lpp-stable.zip

**Comment by ksanislo** [comment]
There's also http://home.intherack.com/lpp-test.zip, which /might/ be better as .3dsx, I'm not really sure what the deal was but Wolvan stated the previous stable build was only solid for .cia versions, and this one was an attempt to increase the stack size to see if it helped with 3dsx.

**Comment by ksanislo** [comment]
Alright, I actually figured out what is going wrong here... When Rinnegatamante removed my use of full text request types, he actually configured the HTTP calls with a default value that causes a crash. To use the current version, you need to provide all of the new "optional" arguments...

downloadFile(url, file, "User-Agent: encTitleKeys.bin-Updater/1.3.1", 1, "") should work properly even with the nightlies, and also give an identifiable User-Agent header in the request. (I don't have time to check this to be 100% certain right now, just fwiw.)

**Comment by MatMaf** [comment]
Just downloaded your zip and it works. Holy crap, this took way too long. Thanks!
