### ISSUE TITLE
Feature Request: Show differences between current database and latest update when a update is avaliable

### ISSUE THREAD

**Issue by deadair3210** [MatMaf/encTitleKeys.bin-Updater#4]
Exactly what it says on the tin, it would be awesome to be able to see the titles that have been added between the version that is new and the version that is currently on the sd card.

**Comment by MatMaf** [comment]
I'm not too sure how easy that would be to implement. You'd need to be able to decrypt and read the title from the .bin first. I'll look into it.

**Comment by deadair3210** [comment]
Perhaps have it behind a option if it takes a while to complete, so it can be optional for people who don't care to know particularly

**Comment by Natanji** [comment]
It's probably easier not decrypting that from the .bin file, but downloading and parsing the list from the titlekeys website, and comparing it with the previous version.

**Comment by JHGitty** [comment]
+1, would be awesome if possible.
