### ISSUE TITLE
Closing the system while the app is open makes the system fail to return from sleep correctly

### ISSUE THREAD

**Issue by deadair3210** [MatMaf/encTitleKeys.bin-Updater#5]
If the system is closed while the app is running, the system will fail to return from sleep correctly, requiring the user to force the system to turn off

**Comment by MatMaf** [comment]
That's currently an issue with lpp-3ds. I'll make a comment about a fix when the latest release (or nightly) of lpp-3ds fixes it, but I'm going to close this for now.
