### ISSUE TITLE
Change icon :)

### ISSUE THREAD

**Issue by tatundria** [MatMaf/encTitleKeys.bin-Updater#6]
Can you change the icon for something more related to nintendo please? Thank you :)

**Comment by JHGitty** [comment]
I think it should use the default freeShop icon, including an update symbol in the center of the icon.

**Comment by MatMaf** [comment]
Planned for 1.3 :)

**Comment by tatundria** [comment]
Any progress on this?

**Comment by MatMaf** [comment]
I'm preparing some versions of v1.3 with alternate banners. Should be out today or tomorrow.

**Comment by tatundria** [comment]
Thank you!!
