### ISSUE TITLE
Download files from specific website

### ISSUE THREAD

**Issue by JHGitty** [MatMaf/encTitleKeys.bin-Updater#7]
It would be nice if I could change the URL where the tool is downloading from.
I like to download my encTitleKeys from this page: https://3ds.titlekeys.com/

Here are the direct download URLs:
encrypted: https://3ds.titlekeys.com/downloadenc
decrypted: https://3ds.titlekeys.com/download

**So it would be awesome to set these URLs in the tool.**

Could you please add a *optional* config file for this?

You may use this path for your config file:
sd:/freeShop/encTitleKeysUpdater.conf

You may also add a URL for the decrypted file for issue #4.

**Comment by MatMaf** [comment]
I'm not sure about an optional config file, since it wouldn't be encTitleKeysUpdater without specifically getting encTitleKeys.bin, but a direct download is planned for 1.3. Getting this working with sockets is what's taking so long.

**Comment by ksanislo** [comment]
@MatMaf no need for sockets, just upgrade lua.

**Comment by MatMaf** [comment]
Fixed in v1.3.
